link-to-tracker: explicitly use ktl libraries
Explicitly use the ktl library to fix the following error in hirsute:

  Traceback (most recent call last):
    File "./stable/link-to-tracker", line 14, in <module>
      from lib.git                            import Git
  ModuleNotFoundError: No module named 'lib.git'

Moreover, get rid of an unused sys.path.append() that is not needed
anymore.

Signed-off-by: Andrea Righi <andrea.righi@canonical.com>
Signed-off-by: Andy Whitcroft <apw@canonical.com>
Signed-off-by: Juerg Haefliger <juergh@canonical.com>