cranky: chroot: add libfuse-dev as dependency for selftests
Compiling selftests locally (by running cranky fdr compileselftests)
will fail with the following error:

fuse_mnt.c:17:10: fatal error: fuse.h: No such file or directory
    17 | #include <fuse.h>
       |          ^~~~~~~~

due to missing libfuse-dev.
This fixes it by always installing libfuse-dev in local chroot.

Signed-off-by: Roxana Nicolescu <roxana.nicolescu@canonical.com>