scripts: remove python2-only executables
Trying to execute these files with a python3 interpreter results in some
SyntaxError, which mean they have not been used since a long time.

    $ python3 web/scripts/gen-bug-report
      File ".../kteam-tools/web/scripts/gen-bug-report", line 464
        retval += '                                    <td >%s</td>\n' % bug['heat'])
        									    ^
    SyntaxError: unmatched ')'

    $ python3 web/scripts/reporter
      File ".../kteam-tools/web/scripts/reporter", line 102
        except GetoptError, error:
               ^^^^^^^^^^^^^^^^^^
    SyntaxError: multiple exception types must be parenthesized

Signed-off-by: Agathe Porte <agathe.porte@canonical.com>
Acked-by: Andy Whitcroft <apw@canonical.com>
Signed-off-by: Agathe Porte <agathe.porte@canonical.com>