ktl/workflow: remove wrong shebang
The file cannot be executed directly because it does imports to the
libraby it is part of:

    $ python3 ktl/workflow.py
    Traceback (most recent call last):
      File "/home/gagath/canonical/kteam-tools/ktl/workflow.py", line 1, in <module>
        from ktl.kernel_series import KernelSeries
    ModuleNotFoundError: No module named 'ktl'

Remove the shebang, the executable flag and add a comment before the
ifmain block to properly run the file (yes, it currently fails but
because argument is missing to workflow.assignee).

Signed-off-by: Agathe Porte <agathe.porte@canonical.com>
Acked-by: Andy Whitcroft <apw@canonical.com>
Signed-off-by: Agathe Porte <agathe.porte@canonical.com>