info/kernel-series: add temporary 'esm' routing for bionic
Commit ("info/kernel-series: mark bionic as ESM") marked bionic as ESM
which expects an 'esm' routing entry which is missing:

Traceback (most recent call last):
  File "/vol2/data/git/kteam-tools/cranky/cmds.d/list-routing", line 88, in <module>
    print_table(handle.source.routing)
  File "/vol2/juergh/git/ubuntu/kteam-tools/ktl/kernel_series.py", line 563, in routing
    return KernelRoutingEntry(self._ks, self, data)
  File "/vol2/juergh/git/ubuntu/kteam-tools/ktl/kernel_series.py", line 83, in __init__
    raise ValueError("unable to map routing alias {}, "
ValueError: unable to map routing alias esm, not listed in series routing table

Fix that by adding a temporary 'esm' routing.

Signed-off-by: Juerg Haefliger <juerg.haefliger@canonical.com>
Acked-by: Thadeu Lima de Souza Cascardo <cascardo@canonical.com>
Signed-off-by: Thadeu Lima de Souza Cascardo <cascardo@canonical.com>