swm: bug -- validate refresh_at datetime
We need to be able to compare all of the refresh_at dates so we can pick
the shortest.  To do this they must all be the same timezone awareness
to avoid hitting these at runtime:

    TypeError: can't compare offset-naive and offset-aware datetimes

Validate the tzinfo and enforce its presence.

Acked-by: Stefan Bader <stefan.bader@canonical.com>
Signed-off-by: Andy Whitcroft <apw@canonical.com>