mainline-builds: adhoc -- Don't apply old packaging patch to current unstable
There's an old packaging patch from the zesty/artful days. The trigger for
it lists the unstable series as well since that made sense back in those
days but no longer. I.e., we don't want it applied when using packaging
files from the (current) unstable series.

This should take care of the (non-fatal) build error message:

*** applying /home/kernel/kteam-tools/mainline-build/./adhoc/zesty-artful-0001-UBUNTU-Debian-Use-default-compression-for-all-packag.patch ...
error: patch failed: debian/rules.d/2-binary-arch.mk:471
error: debian/rules.d/2-binary-arch.mk: patch does not apply
Applying: UBUNTU: [Debian] Use default compression for all packages
Patch failed at 0001 UBUNTU: [Debian] Use default compression for all packages

Acked-by: Andy Whitcroft <andy.whitcroft@canonical.com>
Signed-off-by: Juerg Haefliger <juerg.haefliger@canonical.com>