ktl/kernel_series: Fix KernelSeries class definition for Python2
KernelSeries was recently changed to override __new__(). For that to work
correctly the class needs to inherit from object which needs to be
explicitly specified in Python2 (which we still need to support for
automation that runs on wani).

Otherwise we'll get exceptions like:

Traceback (most recent call last):
 File "scripts/cbd", line 358, in
 app.main()
 File "scripts/cbd", line 302, in main
 this_package_bugs[bug.id] = Bugs.bug_info(bug, now, primary_task)
 File "/home/kernel-ppa/shankbot/kteam-tools/web/scripts/ktl/bugs.py", line 129, in bug_info
 (bug_item['series name'], bug_item['series version']) = bug.series
 File "/home/kernel-ppa/shankbot/kteam-tools/web/scripts/ktl/kernel_bug.py", line 516, in series
 (series_name, series_version) = self._find_series_in_tags(self)
 File "/home/kernel-ppa/shankbot/kteam-tools/web/scripts/ktl/kernel_bug.py", line 494, in _find_series_in_tags
 for series in sorted(self.kernel_series.series, key=KernelSeries.key_series_name):
AttributeError: KernelSeries instance has no attribute 'series'

Signed-off-by: Juerg Haefliger <juerg.haefliger@canonical.com>